import { computed, effect, ErrorHandler, inject, Injectable, signal } from '@angular/core';
import {
  OFFLINE_COMMAND_EXECUTOR,
  OFFLINE_SYNC_CONTEXT,
  type OfflineCommandResult,
  type OfflineSyncSession,
} from './offline-command-executor';
import { OFFLINE_COMMAND_HOOKS } from './offline-command-hooks';
import { OFFLINE_KIT_OPTIONS } from './offline-kit-options';
import { OfflineNetworkService } from './offline-network.service';
import { OfflineReplicaPullService } from './offline-replica-pull.service';
import type {
  OfflineCommand,
  OfflineReplicaSyncState,
  OfflineReplicaRow,
  OfflineReplicaRowKey,
  OfflineReplicaTransaction,
  OfflineRepository,
  OfflineScope,
} from './offline-repository';
import { OFFLINE_REPOSITORY } from './offline-repository';
import {
  canonicalOfflineRemoteIdentity,
  offlineNaturalKeyFromValues,
  type OfflineReplicaRemoteIdentity,
  type OfflineReplicaEntitySchema,
} from './offline-replica-schema';

/** Aggregate synchronization state exposed to application UI. */
export type OfflineSyncState = 'idle' | 'pending' | 'syncing' | 'attention';

/** Mutation and optimistic entity materialization appended atomically to the outbox. */
export interface EnqueueOfflineCommand<T = unknown> {
  scopeId: string;
  aggregateType: string;
  /** Stable UUID generated by the client before the entity is first written. */
  aggregateLocalId: string;
  /**
   * Backward-compatible explicit server-id adoption. When no replica row
   * exists, this initializes its server mapping; use `serverIdHint` for a
   * stale product-side read that must never create such a mapping.
   */
  serverId?: number | null;
  /**
   * Optional consistency check for an already replicated row. It is ignored
   * when the local row does not exist, so it cannot resurrect an
   * AUTO_INCREMENT id after delete/recreate.
   */
  serverIdHint?: number | null;
  operation: string;
  payload: T;
  /** Full local entity value committed to the replica before the command is exposed to the UI. */
  optimisticValue: unknown;
  /**
   * Optimistically hides an existing DB row while retaining its identity and
   * confirmed baseline for durable replay, conflict handling, and discard.
   */
  replicaMutation?: 'upsert' | 'delete';
  baseRevision?: string | number | null;
}

/** Raised before persistence when an outbox payload is not losslessly JSON serializable. */
export class OfflinePayloadValidationError extends Error {
  constructor(message = 'Offline command payload must contain only JSON values') {
    super(message);
    this.name = 'OfflinePayloadValidationError';
  }
}

/** Raised before persistence when retaining another command would exceed the configured durable Outbox capacity. */
export class OfflineOutboxCapacityError extends Error {
  constructor(
    readonly reason: 'command_count' | 'serialized_bytes',
    readonly currentCommands: number,
    readonly currentBytes: number,
  ) {
    super(
      reason === 'command_count'
        ? 'Offline Outbox command limit reached; synchronize or discard a pending command before continuing'
        : 'Offline Outbox storage limit reached; synchronize or discard a pending command before continuing',
    );
    this.name = 'OfflineOutboxCapacityError';
  }
}

const MAX_PARALLEL_AGGREGATES = 3;
const MAX_BACKOFF_MS = 60 * 60 * 1000;
const DEFAULT_MAX_OUTBOX_COMMANDS_PER_USER = 1_000;
const DEFAULT_MAX_OUTBOX_BYTES_PER_USER = 10 * 1024 * 1024;

/** Maintains the optimistic local replica and synchronizes its durable outbox. */
@Injectable({ providedIn: 'root' })
export class OfflineSyncService {
  readonly #network = inject(OfflineNetworkService);
  readonly #repository = inject(OFFLINE_REPOSITORY);
  readonly #executor = inject(OFFLINE_COMMAND_EXECUTOR);
  readonly #context = inject(OFFLINE_SYNC_CONTEXT);
  readonly #hooks = inject(OFFLINE_COMMAND_HOOKS);
  readonly #options = inject(OFFLINE_KIT_OPTIONS);
  readonly #pull = inject(OfflineReplicaPullService);
  readonly #errorHandler = inject(ErrorHandler);
  readonly #commands = signal<OfflineCommand[]>([]);
  readonly #knownScopes = new Map<string, OfflineScope>();
  #activeUserId: number | null = null;
  #flushPromise: Promise<void> | null = null;
  readonly #flushTransitions = new Set<Promise<void>>();
  #generation = 0;
  readonly #sendingTransitions = new Set<Promise<void>>();
  /** Serializes enqueue and acknowledgement projection over the same local replica. */
  #replicaMutationTail: Promise<void> = Promise.resolve();
  #retryTimer: ReturnType<typeof setTimeout> | null = null;
  #initialized = false;
  #lastCommandCreatedAt = 0;

  readonly pendingCommands = this.#commands.asReadonly();
  readonly pendingCount = computed(() => this.pendingCommands().length);
  readonly conflicts = computed(() => this.#commands().filter((command) => command.state === 'conflict'));
  readonly syncState = computed<OfflineSyncState>(() => {
    const commands = this.#commands();
    if (commands.some((command) => ['blocked_auth', 'rejected', 'conflict'].includes(command.state))) return 'attention';
    if (commands.some((command) => command.state === 'sending')) return 'syncing';
    return commands.length > 0 ? 'pending' : 'idle';
  });

  constructor() {
    effect(() => {
      const connected = this.#network.connected();
      if (this.#initialized && connected) this.#flushInBackground();
    });
  }

  async initialize(): Promise<void> {
    if (this.#initialized) return;
    await this.#repository.initialize();
    await this.#discoverScopes();
    const commands = await this.#readKnownCommands();
    await Promise.all(
      commands
        .filter((command) => command.state === 'sending')
        .map((command) => this.#repository.putCommand({ ...command, state: 'pending' })),
    );
    this.#initialized = true;
    await this.#refreshState();
    if (this.#network.connected()) this.#flushInBackground();
  }

  noteScope(scope: OfflineScope): void {
    this.#knownScopes.set(this.#scopeKey(scope), scope);
  }

  async reloadPendingCommands(): Promise<void> {
    await this.initialize();
    await this.#refreshState();
  }

  async refreshSession(): Promise<void> {
    await this.initialize();
    await this.#discoverScopes();
    await this.#restoreInterruptedCommands();
    await this.#refreshState();
    if (this.#network.connected()) this.#flushInBackground();
  }

  /** Restores local outbox visibility without enabling pull or replay transport. */
  async refreshLocalSession(): Promise<void> {
    await this.initialize();
    await this.#discoverLocalScopes();
    await this.#restoreInterruptedCommands();
    await this.#refreshState();
  }

  async resetSession(): Promise<void> {
    this.revokeSession();
    await Promise.allSettled([this.#replicaMutationTail, ...this.#flushTransitions]);
    await this.#waitForSendingTransitions();
    await this.#restoreInterruptedCommands();
    this.#activeUserId = null;
    this.#knownScopes.clear();
    this.#commands.set([]);
    this.#scheduleRetry(null);
  }

  /** Synchronously invalidate in-flight enqueue and transport work owned by the current session. */
  revokeSession(): void {
    this.#invalidateFlush();
  }

  enqueue<T>(request: EnqueueOfflineCommand<T>, options: { flush?: boolean } = {}): Promise<string> {
    const generation = this.#generation;
    return this.#serializeReplicaMutation(() => this.#enqueue(request, options, generation));
  }

  /**
   * Serializes a product-owned replica projection with enqueue and command ACK
   * reconciliation. For read/derive/write cache updates, prefer
   * `runSerializedReplicaMutation` so the read is serialized as well.
   */
  async transactReplica(transaction: OfflineReplicaTransaction): Promise<void> {
    await this.runSerializedReplicaMutation(async (repository) => {
      await repository.transactReplica(transaction);
    });
  }

  /**
   * Runs a product cache's replica read/derive/write sequence atomically with
   * enqueue and ACK projection. Use this for any repository reads that inform
   * a later transaction; `transactReplica` alone only serializes the write.
   */
  runSerializedReplicaMutation<T>(operation: (repository: OfflineRepository) => Promise<T>): Promise<T> {
    const generation = this.#generation;
    return this.#serializeReplicaMutation(async () => {
      await this.initialize();
      if (!this.#isCurrent(generation)) throw new Error('Offline session changed before serialized replica mutation.');
      const result = await operation(this.#repository);
      if (this.#isCurrent(generation)) await this.#refreshState(generation);
      return result;
    });
  }

  #serializeReplicaMutation<T>(operation: () => Promise<T>): Promise<T> {
    const mutation = this.#replicaMutationTail.then(operation);
    this.#replicaMutationTail = mutation.then(
      () => undefined,
      () => undefined,
    );
    return mutation;
  }

  async #enqueue<T>(request: EnqueueOfflineCommand<T>, options: { flush?: boolean }, generation: number): Promise<string> {
    await this.initialize();
    const session = await this.#getLocalSession();
    if (!session) throw new Error('Cannot enqueue an offline command without an authenticated user');
    const userId = session.userId;
    this.#setActiveUser(userId);
    const scope = { userId, scopeId: request.scopeId };
    this.noteScope(scope);
    const aggregateLocalId = request.aggregateLocalId;
    const normalized = await this.#normalizeEnqueueRequest(scope, request);
    const optimisticValue = request.optimisticValue;
    const commandId = crypto.randomUUID();
    const command: OfflineCommand = {
      ...scope,
      commandId,
      aggregateType: request.aggregateType,
      aggregateLocalId,
      operation: request.operation,
      payload: normalized.payload,
      optimisticValue,
      replicaMutation: request.replicaMutation ?? 'upsert',
      payloadHash: await this.#payloadHash(normalized.payload),
      baseRevision: normalized.baseRevision,
      state: 'pending',
      attempts: 0,
      retryAt: null,
      createdAt: await this.#nextCommandCreatedAt(userId),
      lastErrorCode: null,
    };
    await this.#assertOutboxCapacity(userId, command);
    const entityType = this.#entityType(command);
    const schema = this.#entitySchema(entityType);
    if (request.replicaMutation === 'delete' && !this.#repository.getReplicaRowIncludingPendingDelete) {
      throw new Error('Offline repository does not support durable replica delete tombstones.');
    }
    const existing = await this.#getReplicaRowForSync(scope, entityType, aggregateLocalId);
    const initialServerId = this.#initialServerId(existing?.serverId ?? null, request.serverId);
    this.#assertServerIdHint(existing?.serverId ?? null, request.serverIdHint);
    const naturalKey = offlineNaturalKeyFromValues(schema, optimisticValue);
    const remoteIdentity: OfflineReplicaRemoteIdentity | null =
      schema.identity.kind === 'serverId'
        ? initialServerId === null
          ? null
          : { serverId: initialServerId }
        : schema.identity.kind === 'naturalKey'
          ? { naturalKey: naturalKey! }
          : null;
    if (schema.identity.kind === 'naturalKey' && request.serverId != null) {
      throw new Error(`Offline replica source "${entityType}" does not define a serverId field.`);
    }
    if (schema.identity.kind === 'naturalKey') {
      const canonicalValuesKey = canonicalOfflineRemoteIdentity(schema, remoteIdentity!);
      if (
        existing &&
        canonicalOfflineRemoteIdentity(schema, { naturalKey: offlineNaturalKeyFromValues(schema, existing.values)! }) !== canonicalValuesKey
      ) {
        throw new Error(`Offline replica naturalKey is immutable and must match optimistic values for "${entityType}".`);
      }
    }
    if (remoteIdentity !== null) {
      const mapped = await this.#repository.getReplicaRowByRemoteIdentity(scope, entityType, remoteIdentity);
      if (mapped !== null && mapped.localId !== aggregateLocalId) {
        if (remoteIdentity.serverId !== undefined) {
          throw new Error(`Offline replica serverId ${String(remoteIdentity.serverId)} is already mapped to localId ${mapped.localId}.`);
        }
        throw new Error(`Offline replica remote identity is already mapped to localId ${mapped.localId}.`);
      }
    }
    const optimisticRow: OfflineReplicaRow = {
      ...scope,
      sourceKey: entityType,
      localId: aggregateLocalId,
      serverId: initialServerId,
      values: optimisticValue,
      confirmedValues: existing?.confirmedValues ?? existing?.values ?? null,
      serverRevision: existing?.serverRevision ?? normalized.baseRevision,
      fetchedAt: Date.now(),
      syncState: 'pending',
      visibility: request.replicaMutation === 'delete' ? 'pending_delete' : 'present',
    };
    if (generation !== this.#generation) {
      throw new Error('Offline session changed before the command could be persisted');
    }
    await this.#repository.transactReplica({ putRows: [optimisticRow], putCommands: [command] });
    await this.#refreshState();
    if (options.flush !== false && this.#network.connected()) this.#flushInBackground();
    return commandId;
  }

  async #assertOutboxCapacity(userId: number, command: OfflineCommand): Promise<void> {
    const commands = this.#repository.getCommandsForUser
      ? await this.#repository.getCommandsForUser(userId)
      : (
          await Promise.all(
            [...this.#knownScopes.values()].filter((scope) => scope.userId === userId).map((scope) => this.#repository.getCommands(scope)),
          )
        ).flat();
    const maxCommands = this.#options.outboxLimits?.maxCommandsPerUser ?? DEFAULT_MAX_OUTBOX_COMMANDS_PER_USER;
    const maxBytes = this.#options.outboxLimits?.maxBytesPerUser ?? DEFAULT_MAX_OUTBOX_BYTES_PER_USER;
    const currentBytes = this.#serializedOutboxBytes(commands);
    if (commands.length >= maxCommands) {
      throw new OfflineOutboxCapacityError('command_count', commands.length, currentBytes);
    }
    const nextBytes = currentBytes + this.#serializedOutboxBytes([command]);
    if (nextBytes > maxBytes) {
      throw new OfflineOutboxCapacityError('serialized_bytes', commands.length, currentBytes);
    }
  }

  #serializedOutboxBytes(commands: readonly OfflineCommand[]): number {
    return new TextEncoder().encode(JSON.stringify(commands)).byteLength;
  }

  async discard(commandId: string, options: { flush?: boolean } = {}): Promise<void> {
    await this.initialize();
    const command = (await this.#readKnownCommands()).find((item) => item.commandId === commandId);
    if (!command) return;
    this.#invalidateFlush();
    await this.#waitForSendingTransitions();
    await this.#discardCommands([command]);
    await this.#hooks.onCommandRemoved?.(command);
    await this.#restoreInterruptedCommands();
    await this.#refreshState();
    if (options.flush !== false && this.#network.connected()) this.#flushInBackground();
  }

  async discardAllPending(): Promise<void> {
    await this.initialize();
    this.#invalidateFlush();
    await this.#waitForSendingTransitions();
    const commands = await this.#readKnownCommands();
    await this.#discardCommands(commands);
    await Promise.all(commands.map((command) => this.#hooks.onCommandRemoved?.(command)));
    await this.#refreshState();
  }

  #flushInBackground(): void {
    void this.flush().catch((error) => this.#errorHandler.handleError(error));
  }

  flush(): Promise<void> {
    if (this.#flushPromise) return this.#flushPromise;
    const generation = this.#generation;
    const promise = this.#runFlush(generation).finally(() => {
      this.#flushTransitions.delete(promise);
      if (this.#flushPromise === promise) this.#flushPromise = null;
    });
    this.#flushPromise = promise;
    this.#flushTransitions.add(promise);
    return promise;
  }

  async #runFlush(generation: number): Promise<void> {
    if (!this.#isCurrent(generation)) return;
    if (!this.#network.connected()) {
      await this.#refreshState(generation);
      return;
    }
    if (!(await this.#discoverScopes(generation))) return;
    for (const scope of this.#knownScopes.values()) {
      if (!this.#isCurrent(generation) || !this.#network.connected()) return;
      await this.#pull.pull(scope);
    }
    while (this.#network.connected() && this.#isCurrent(generation)) {
      const groups = this.#eligibleAggregateGroups(await this.#readKnownCommands());
      if (!this.#isCurrent(generation)) return;
      if (groups.length === 0) break;
      let cursor = 0;
      const workers = Array.from({ length: Math.min(MAX_PARALLEL_AGGREGATES, groups.length) }, async () => {
        while (cursor < groups.length) {
          const group = groups[cursor++];
          if (group && this.#isCurrent(generation)) await this.#sendAggregate(group, generation);
        }
      });
      await Promise.all(workers);
    }
    await this.#refreshState(generation);
  }

  #eligibleAggregateGroups(commands: OfflineCommand[]): OfflineCommand[][] {
    const now = Date.now();
    const groups = new Map<string, OfflineCommand[]>();
    for (const command of commands) {
      const key = this.#aggregateKey(command);
      const group = groups.get(key) ?? [];
      group.push(command);
      groups.set(key, group);
    }
    return [...groups.values()].filter((group) => {
      const head = group[0];
      return head?.state === 'pending' || (head?.state === 'retry_wait' && (head.retryAt ?? 0) <= now);
    });
  }

  async #sendAggregate(commands: OfflineCommand[], generation: number): Promise<void> {
    for (const command of commands) {
      if (!this.#isCurrent(generation)) return;
      if (command.state === 'retry_wait' && (command.retryAt ?? 0) > Date.now()) break;
      if (!['pending', 'retry_wait'].includes(command.state)) break;
      const sending: OfflineCommand = {
        ...command,
        state: 'sending',
        attempts: command.attempts + 1,
        retryAt: null,
        lastErrorCode: null,
      };
      await this.#putSendingCommand(sending);
      if (!this.#isCurrent(generation)) return;
      await this.#refreshState(generation);
      if (!this.#isCurrent(generation)) return;
      const row = await this.#rowForCommand(sending);
      if (!row) throw new Error(`Offline replica row not found: ${sending.aggregateType}/${sending.aggregateLocalId}`);
      let result: OfflineCommandResult;
      try {
        const schema = this.#entitySchema(row.sourceKey);
        const naturalKey = offlineNaturalKeyFromValues(schema, row.values);
        result = await this.#executor.execute(sending, {
          localId: row.localId,
          serverId: row.serverId,
          ...(naturalKey !== null ? { naturalKey } : {}),
        });
      } catch (error) {
        if (!this.#isCurrent(generation)) return;
        if (!this.#isClassifiableTransportError(error)) throw error;
        const failed = this.#failedCommand(sending, error);
        await this.#repository.transactReplica({
          putRows: [{ ...row, syncState: this.#replicaState(failed.state) }],
          putCommands: [failed],
        });
        if (failed.state === 'retry_wait') this.#scheduleRetry(failed.retryAt);
        break;
      }
      if (!this.#isCurrent(generation)) return;
      await this.#completeCommand(commands, sending, result, generation);
    }
  }

  async #normalizeEnqueueRequest<T>(
    scope: OfflineScope,
    request: EnqueueOfflineCommand<T>,
  ): Promise<{ payload: T; baseRevision: string | number | null }> {
    let baseRevision = request.baseRevision ?? null;
    let payload = request.payload;
    const aggregateLocalId = request.aggregateLocalId;
    const row = await this.#getReplicaRowForSync(scope, this.#entityType(request), aggregateLocalId);
    if (row?.serverRevision != null && row.serverRevision !== baseRevision) {
      const rebased = this.#executor.withServerRevision(
        { ...scope, ...request, aggregateLocalId, payload, baseRevision } as OfflineCommand,
        row.serverRevision,
      );
      baseRevision = row.serverRevision;
      payload = rebased.payload as T;
    }
    return { payload, baseRevision };
  }

  async #completeCommand(
    commands: OfflineCommand[],
    command: OfflineCommand,
    result: OfflineCommandResult,
    generation: number,
  ): Promise<void> {
    return this.#serializeReplicaMutation(() => this.#completeCommandLocked(commands, command, result, generation));
  }

  async #completeCommandLocked(
    commands: OfflineCommand[],
    command: OfflineCommand,
    result: OfflineCommandResult,
    generation: number,
  ): Promise<void> {
    if (result.clearServerId === true && result.serverId !== undefined) {
      throw new Error('Offline command cannot return serverId and clearServerId together.');
    }
    if (result.clearServerId === true && result.serverRevision !== undefined) {
      throw new Error('Offline command cannot return serverRevision and clearServerId together.');
    }
    // An enqueue may have completed while transport was in flight. Re-read the
    // aggregate immediately before the atomic acknowledgement transaction so a
    // delete ACK cannot remove a row that has already been re-added locally.
    const latestCommands = (await this.#readKnownCommands()).filter(
      (candidate) => this.#aggregateKey(candidate) === this.#aggregateKey(command),
    );
    const latestIndex = latestCommands.findIndex((candidate) => candidate.commandId === command.commandId);
    if (latestIndex < 0) return;
    const revision = result.serverRevision;
    const following = latestCommands.slice(latestIndex + 1);
    const rebased =
      result.clearServerId === true
        ? following.map((item) => {
            if (!this.#executor.withoutServerRevision) {
              throw new Error('Offline command executor must implement withoutServerRevision to recreate a deleted serverId row.');
            }
            return this.#executor.withoutServerRevision(item);
          })
        : revision === undefined
          ? following
          : following.map((item) => this.#executor.withServerRevision(item, revision));
    latestCommands.splice(latestIndex + 1, rebased.length, ...rebased);
    const current = await this.#rowForCommand(command);
    if (!this.#isCurrent(generation)) return;
    if (!current) {
      throw new Error(`Offline replica row disappeared while completing command ${command.commandId}.`);
    }
    this.#assertServerRevision(result.serverRevision);
    const removesReplica = result.removeReplica === true || command.replicaMutation === 'delete';
    if (result.clearServerId === true && !removesReplica) {
      throw new Error('Offline command can clear serverId only for a confirmed replica removal.');
    }
    const confirmedValues = removesReplica ? null : (result.confirmedValues ?? command.optimisticValue);
    const schema = this.#entitySchema(current.sourceKey);
    this.#assertCommandResultIdentity(schema, current, result);
    const serverId = result.clearServerId === true ? null : this.#resolvedServerId(current.serverId, result.serverId);
    const row = {
      ...current,
      // The row may have received a local-only patch (for example, a UI
      // projection was integrated) while this command was in flight. Keep the
      // current durable optimistic state instead of restoring the stale
      // command snapshot when later commands remain queued.
      values: rebased.length > 0 ? current.values : confirmedValues,
      confirmedValues,
      serverId,
      serverRevision: result.clearServerId === true ? null : (revision ?? current.serverRevision),
      fetchedAt: Date.now(),
      syncState: rebased.length > 0 ? ('pending' as const) : ('confirmed' as const),
      visibility: rebased.at(-1)?.replicaMutation === 'delete' ? ('pending_delete' as const) : ('present' as const),
    };
    if (!this.#isCurrent(generation)) return;
    await this.#repository.transactReplica({
      putRows: removesReplica && rebased.length === 0 ? undefined : [row],
      releaseServerIds:
        result.clearServerId === true && current.serverId !== null && !(removesReplica && rebased.length === 0)
          ? [
              {
                userId: current.userId,
                scopeId: current.scopeId,
                sourceKey: current.sourceKey,
                localId: current.localId,
                serverId: current.serverId,
              },
            ]
          : undefined,
      removeRows: removesReplica && rebased.length === 0 ? [current] : undefined,
      putCommands: rebased,
      removeCommandIds: [command.commandId],
    });
    commands.splice(0, commands.length, ...latestCommands);
  }

  async #rowForCommand(command: OfflineCommand): Promise<OfflineReplicaRow | null> {
    const scope = { userId: command.userId, scopeId: command.scopeId };
    const entityType = this.#entityType(command);
    return this.#getReplicaRowForSync(scope, entityType, command.aggregateLocalId);
  }

  #getReplicaRowForSync(scope: OfflineScope, sourceKey: string, localId: string): Promise<OfflineReplicaRow | null> {
    return (
      this.#repository.getReplicaRowIncludingPendingDelete?.(scope, sourceKey, localId) ??
      this.#repository.getReplicaRow(scope, sourceKey, localId)
    );
  }

  #replicaState(state: OfflineCommand['state']): OfflineReplicaSyncState {
    if (state === 'blocked_auth' || state === 'rejected' || state === 'conflict') return state;
    return 'pending';
  }

  #entityType(command: Pick<OfflineCommand, 'operation' | 'aggregateType'>): string {
    return this.#hooks.entityType(command);
  }

  #entitySchema(sourceKey: string): OfflineReplicaEntitySchema<Record<string, unknown>> {
    const schema = this.#options.replicaSchema.entities.find((entity) => entity.sourceKey === sourceKey);
    if (!schema) throw new Error(`Unknown offline replica source key "${sourceKey}".`);
    return schema;
  }

  async #discardCommands(discarded: readonly OfflineCommand[]): Promise<void> {
    const all = await this.#readKnownCommands();
    const discardedIds = new Set(discarded.map((command) => command.commandId));
    const affected = new Map<string, OfflineCommand>();
    for (const command of discarded) affected.set(this.#aggregateKey(command), command);
    const putRows: OfflineReplicaRow[] = [];
    const removeRows: OfflineReplicaRowKey[] = [];
    for (const [key, command] of affected) {
      const row = await this.#rowForCommand(command);
      if (!row) continue;
      const remaining = all.filter((item) => !discardedIds.has(item.commandId) && this.#aggregateKey(item) === key);
      if (remaining.length === 0 && row.confirmedValues === null) {
        removeRows.push(row);
      } else {
        putRows.push({
          ...row,
          values: remaining.length > 0 ? remaining.at(-1)!.optimisticValue : row.confirmedValues,
          syncState: remaining.length > 0 ? 'pending' : 'confirmed',
          visibility: remaining.at(-1)?.replicaMutation === 'delete' ? 'pending_delete' : 'present',
        });
      }
    }
    await this.#repository.transactReplica({
      putRows,
      removeRows,
      removeCommandIds: [...discardedIds],
    });
  }

  #aggregateKey(command: OfflineCommand): string {
    const sourceKey = this.#entityType(command);
    const schema = this.#options.replicaSchema.entities.find((entity) => entity.sourceKey === sourceKey);
    if (!schema) throw new Error(`Unknown offline replica source key "${sourceKey}".`);
    const partition = schema.scope === 'user' ? 'user' : `partition:${command.scopeId}`;
    return `${command.userId}:${partition}:${sourceKey}:${command.aggregateLocalId}`;
  }

  #failedCommand(command: OfflineCommand, error: unknown): OfflineCommand {
    const status = this.#errorStatus(error);
    if (status === 401 || status === 403) return { ...command, state: 'blocked_auth', lastErrorCode: String(status) };
    if (status === 409 || status === 412) return { ...command, state: 'conflict', lastErrorCode: String(status) };
    if (status >= 400 && status < 500 && status !== 429) {
      return { ...command, state: 'rejected', lastErrorCode: String(status) };
    }
    const retryAt = Date.now() + Math.min(MAX_BACKOFF_MS, 1000 * 2 ** Math.max(0, command.attempts - 1));
    return { ...command, state: 'retry_wait', retryAt, lastErrorCode: status > 0 ? String(status) : 'network' };
  }

  #errorStatus(error: unknown): number {
    if (typeof error !== 'object' || error === null) return 0;
    const status = (error as { status?: unknown }).status;
    return typeof status === 'number' ? status : 0;
  }

  #isClassifiableTransportError(error: unknown): boolean {
    if (typeof error !== 'object' || error === null) return false;
    const status = (error as { status?: unknown }).status;
    return typeof status === 'number' && Number.isInteger(status) && status >= 0;
  }

  #assertServerRevision(revision: string | number | undefined): void {
    if (typeof revision === 'number' && !Number.isFinite(revision)) {
      throw new Error(`Offline command returned invalid serverRevision ${String(revision)}.`);
    }
  }

  #resolvedServerId(current: number | null, incoming: number | undefined): number | null {
    if (incoming === undefined) return current;
    if (!Number.isSafeInteger(incoming) || incoming <= 0) {
      throw new Error(`Offline command returned invalid serverId ${String(incoming)}.`);
    }
    if (current !== null && current !== incoming) {
      throw new Error(`Offline replica serverId is immutable: current=${current}, incoming=${incoming}.`);
    }
    return incoming;
  }

  #initialServerId(current: number | null, incoming: number | null | undefined): number | null {
    return incoming === null || incoming === undefined ? current : this.#resolvedServerId(current, incoming);
  }

  #assertServerIdHint(current: number | null, hint: number | null | undefined): void {
    if (hint === null || hint === undefined) return;
    if (!Number.isSafeInteger(hint) || hint <= 0) {
      throw new Error(`Offline command returned invalid serverId hint ${String(hint)}.`);
    }
    if (current !== null && current !== hint) {
      throw new Error(`Offline replica serverId hint does not match current=${current}: incoming=${hint}.`);
    }
  }

  #assertCommandResultIdentity(
    schema: OfflineReplicaEntitySchema<Record<string, unknown>>,
    current: OfflineReplicaRow,
    result: OfflineCommandResult,
  ): void {
    if (result.clearServerId === true && schema.identity.kind !== 'serverId') {
      throw new Error(`Offline command cannot clear serverId for source "${schema.sourceKey}".`);
    }
    if (schema.identity.kind === 'naturalKey' && result.serverId !== undefined) {
      throw new Error(`Offline command returned serverId for naturalKey source "${schema.sourceKey}".`);
    }
    if (schema.identity.kind !== 'serverId' && result.serverId !== undefined) {
      throw new Error(`Offline command returned serverId for source "${schema.sourceKey}" without serverId identity.`);
    }
    if (schema.identity.kind === 'naturalKey') {
      const confirmedValues = result.confirmedValues ?? current.values;
      const currentKey = offlineNaturalKeyFromValues(schema, current.values)!;
      const confirmedKey = offlineNaturalKeyFromValues(schema, confirmedValues)!;
      if (
        canonicalOfflineRemoteIdentity(schema, { naturalKey: currentKey }) !==
        canonicalOfflineRemoteIdentity(schema, { naturalKey: confirmedKey })
      ) {
        throw new Error(`Offline replica naturalKey is immutable for "${schema.sourceKey}".`);
      }
    }
  }

  async #discoverScopes(generation = this.#generation): Promise<boolean> {
    const session = await this.#context.getSession();
    if (!this.#isCurrent(generation)) return false;
    if (!session) {
      return false;
    }
    this.#setActiveUser(session.userId);
    this.#knownScopes.clear();
    for (const scope of session.scopes) this.#knownScopes.set(this.#scopeKey(scope), scope);
    return true;
  }

  async #discoverLocalScopes(generation = this.#generation): Promise<boolean> {
    const session = await this.#getLocalSession();
    if (!this.#isCurrent(generation)) return false;
    if (!session) {
      this.#activeUserId = null;
      this.#knownScopes.clear();
      return true;
    }
    this.#setActiveUser(session.userId);
    this.#knownScopes.clear();
    for (const scope of session.scopes) this.#knownScopes.set(this.#scopeKey(scope), scope);
    return true;
  }

  #getLocalSession(): Promise<OfflineSyncSession | null> {
    return this.#context.getLocalSession?.() ?? this.#context.getSession();
  }

  #setActiveUser(userId: number): void {
    if (this.#activeUserId === userId) return;
    this.#knownScopes.clear();
    this.#activeUserId = userId;
    this.#lastCommandCreatedAt = 0;
  }

  async #readKnownCommands(): Promise<OfflineCommand[]> {
    const commands = (await Promise.all([...this.#knownScopes.values()].map((scope) => this.#repository.getCommands(scope))))
      .flat()
      .sort(compareOfflineCommands);
    this.#rememberCreatedAt(commands);
    return commands;
  }

  async #nextCommandCreatedAt(userId: number): Promise<number> {
    const commands = this.#repository.getCommandsForUser
      ? await this.#repository.getCommandsForUser(userId)
      : await this.#readKnownCommands();
    this.#rememberCreatedAt(commands);
    const createdAt = Math.max(Date.now(), this.#lastCommandCreatedAt + 1);
    this.#lastCommandCreatedAt = createdAt;
    return createdAt;
  }

  #rememberCreatedAt(commands: readonly OfflineCommand[]): void {
    for (const command of commands) this.#lastCommandCreatedAt = Math.max(this.#lastCommandCreatedAt, command.createdAt);
  }

  async #refreshState(generation = this.#generation): Promise<void> {
    const commands = await this.#readKnownCommands();
    if (!this.#isCurrent(generation)) return;
    this.#commands.set(commands);
    const nextRetry = commands
      .filter((command) => command.state === 'retry_wait' && command.retryAt !== null)
      .reduce<number | null>((earliest, command) => Math.min(earliest ?? command.retryAt!, command.retryAt!), null);
    this.#scheduleRetry(nextRetry);
  }

  #scheduleRetry(retryAt: number | null): void {
    if (this.#retryTimer) clearTimeout(this.#retryTimer);
    this.#retryTimer = null;
    if (retryAt === null) return;
    this.#retryTimer = setTimeout(
      () => {
        this.#retryTimer = null;
        if (this.#network.connected()) this.#flushInBackground();
      },
      Math.max(0, retryAt - Date.now()),
    );
  }

  #invalidateFlush(): void {
    this.#generation += 1;
    this.#flushPromise = null;
    this.#scheduleRetry(null);
  }

  #isCurrent(generation: number): boolean {
    return generation === this.#generation;
  }

  async #restoreInterruptedCommands(): Promise<void> {
    const commands = await this.#readKnownCommands();
    await Promise.all(
      commands
        .filter((command) => command.state === 'sending')
        .map((command) => this.#repository.putCommand({ ...command, state: 'pending' })),
    );
  }

  #putSendingCommand(command: OfflineCommand): Promise<void> {
    const transition = this.#repository.putCommand(command);
    this.#sendingTransitions.add(transition);
    void transition.then(
      () => this.#sendingTransitions.delete(transition),
      () => this.#sendingTransitions.delete(transition),
    );
    return transition;
  }

  async #waitForSendingTransitions(): Promise<void> {
    await Promise.allSettled([...this.#sendingTransitions]);
  }

  async #payloadHash(payload: unknown): Promise<string> {
    const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(this.#canonicalJson(payload)));
    return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('');
  }

  #canonicalJson(value: unknown): string {
    if (Array.isArray(value)) return `[${value.map((item) => this.#canonicalJson(item)).join(',')}]`;
    if (value !== null && typeof value === 'object') {
      if (Object.getPrototypeOf(value) !== Object.prototype) {
        throw new OfflinePayloadValidationError();
      }
      return `{${Object.entries(value)
        .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
        .map(([key, item]) => `${JSON.stringify(key)}:${this.#canonicalJson(item)}`)
        .join(',')}}`;
    }
    if (typeof value === 'number' && !Number.isFinite(value)) {
      throw new OfflinePayloadValidationError();
    }
    const serialized = JSON.stringify(value);
    if (typeof serialized !== 'string') {
      throw new OfflinePayloadValidationError();
    }
    return serialized;
  }

  #scopeKey(scope: OfflineScope): string {
    return `${scope.userId}:${scope.scopeId}`;
  }
}

function compareOfflineCommands(left: OfflineCommand, right: OfflineCommand): number {
  return left.createdAt - right.createdAt || (left.commandId < right.commandId ? -1 : left.commandId > right.commandId ? 1 : 0);
}
