name: Lint
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Cache Angular
        uses: actions/cache@v5
        with:
          path: .angular/cache
          key: ${{ runner.os }}-angular-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-angular-${{ hashFiles('package-lock.json') }}-
            ${{ runner.os }}-angular-
      - run: npm ci
      - run: npm run lint
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ demo, photo-editor, scroll-header, scroll-strategies]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Cache Angular
        uses: actions/cache@v5
        with:
          path: .angular/cache
          key: ${{ runner.os }}-angular-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-angular-${{ hashFiles('package-lock.json') }}-
            ${{ runner.os }}-angular-
      - run: npm ci
      - run: npm run build
      - run: npm run test -- ${{ matrix.project }} --watch=false
